thinkphp-exception

  #自定义异常错误
  #exception('Index',1001);\r\n
  #exception('Index',1001,'msg',['test'=>'test']);\r\n
  #返回成功\r\n
  #Response::send('请求成功');\r\n
  #Response::send('创建|修改|更新成功',ApiCode::CREATED);
